### ISSUE TITLE
[forum] Bericht verwijderen lukt niet

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#398]
Zoals de titel doet vermoeden kan ik een bericht niet verwijderen, het klikken op de knop "lukt niet"
![image](https://user-images.githubusercontent.com/7062995/176013692-8433abe3-4388-4477-ac54-30c36482eabc.png)

**Comment by hvdmeer** [comment]
Ik laat het bericht even staan, maar ik vermoed dat verwijderen via de beheerdeskant wel zou moeten lukken

**Comment by hans2103** [comment]
@hvdmeer zie je in de javascript console een foutmelding?

**Comment by hans2103** [comment]
```
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in 
    {
        "{closeButton} click": function() {
            this.parent.close();
        },
        "{submitButton} click": function() {
            this.form().submit();
        }
    }
    
    at p (jquery.min.js?1655885774:2:1077)
    at Function.each (jquery.min.js?1655885774:2:2937)
    at Function.setBindings (easydiscuss-basic-5.0.9.js:2:15940)
    at Function.open (easydiscuss-basic-5.0.9.js:2:14051)
    at Function.open (easydiscuss-basic-5.0.9.js:2:14925)
    at Function.reopen (easydiscuss-basic-5.0.9.js:2:14994)
    at Object.<anonymous> (easydiscuss-basic-5.0.9.js:2:14680)
    at c (jquery.min.js?1655885774:2:28294)
    at Object.fireWith [as resolveWith] (jquery.min.js?1655885774:2:29039)
    at Object.resolve (easydiscuss-basic-5.0.9.js:3:7289)
```

**Comment by hans2103** [comment]
lokaal: 
<img width="416" alt="Schermafbeelding 2022-06-27 om 21 32 17" src="https://user-images.githubusercontent.com/639822/176021202-81895503-b2ac-43ba-9ca9-dd60714703a5.png">

**Comment by hans2103** [comment]
ook op joomlacommunity.nl is het issue voor het moment opgelost. 
Ik heb de System plugin HTTPHeaders hiervoor uit moeten schakelen.
